### PR TITLE
fix(Playground): handle apiKey in query, cookies and headers based on `in` property

### LINKED ISSUE #294: API key query parameters sent as headers instead
### Current behavior

My security scheme is as follows:
`"securitySchemes": {
      "APIKeyQuery": {
        "type": "apiKey",
        "in": "query",
        "name": "api_key"
      }`

When clicking "Try it out", the browser sends:
```
GET /api/endpoint
Headers: Api_key: example_key
```

### Desired behavior

`GET /api/endpoint?api_key=example_key`

### Steps to reproduce
**Environment:**
- vitepress-openapi@0.1.7
- "vitepress": "^1.6.3"
- browser: any

add `"securitySchemes": {
      "APIKeyQuery": {
        "type": "apiKey",
        "in": "query",
        "name": "api_key"
      }` to your openapi.json
and see that it goes to headers instead of query

### Logs and Error Messages

This causes API calls to fail since our server expects the API key as a query parameter, making the interactive documentation unusable.

### Other Information

Can you please fix this?

### PR DESCRIPTION
**Pull request by enzonotario**
# Description

Allow to use apiKeys in headers/query

## Related issues/external references

Fixes #294 

## Types of changes

- Bug fix

### CODE REVIEW

File: src/lib/codeSamples/buildRequest.ts [hunk 1]
```diff
@@ -120,6 +120,77 @@ function getQuery(
...
+    if (authorization.type === 'apiKey' && authorization.in === 'query') {
+      const value = unref(authorization.value ?? authorization.name ?? '')
+      if (!value) {
+        continue
+      }
+      const name = authorization.name ?? ''
+      if (!name) {
+        continue
+      }
+      params[name] = value
```
Comment (nataliiabyk) [inline src/lib/codeSamples/buildRequest.ts:158]: maybe `value.trim()` could help?

Comment (enzonotario) [reply src/lib/codeSamples/buildRequest.ts:158]: Lets discuss this in #294
